version: "3.0"
services:
  database:
    image: postgres
    container_name: "postgres_db"
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    networks:
      - fullstack
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "adhd-server"
    env_file: .env.dev
    restart: on-failure
    depends_on:
      - database
    links:
      - database
    networks:
      - fullstack
    ports:
      - "8080:8080"
volumes:
  data:

networks:
  fullstack:
    driver: bridge
